name: CI
on: [push]
permissions:
  contents: read
env:
  DENO_DIR: .deno
jobs:
  Lint:
    strategy:
      matrix:
        deno: [v1.x]
        os: [macos-12, ubuntu-22.04]
    name: Lint (deno-${{ matrix.deno }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ matrix.os }}-${{ hashFiles('deno.lock') }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check Code Format
        run: deno fmt --check
      - name: Lint Code
        run: deno lint
  Test:
    strategy:
      matrix:
        deno: [v1.x]
        os: [macos-12, ubuntu-22.04]
    name: Test (deno-${{ matrix.deno }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ matrix.os }}-${{ hashFiles('deno.lock') }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run Test Cases
        if: matrix.os != 'ubuntu-22.04'
        run: deno test
      - name: Run Test Cases
        if: matrix.os == 'ubuntu-22.04'
        run: |
          deno test --coverage=.coverage.local
          deno coverage --lcov --output=.coverage.local.lcov .coverage.local
      - name: Upload Coverage Info
        if: matrix.os == 'ubuntu-22.04'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage.local.lcov
